/*
 * Ent Schema API
 *
 * This is an auto generated API description made out of an Ent schema definition
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/mattn/entgo-openapi-example/crud"
	"github.com/mattn/entgo-openapi-example/swagger"
)

func main() {
	err := crud.NewClient().Schema.Create(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Server started")

	router := swagger.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
