/*
 * Ent Schema API
 *
 * This is an auto generated API description made out of an Ent schema definition
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse400 struct {
	Code int32 `json:"code,omitempty"`

	Errors *interface{} `json:"errors,omitempty"`

	Status string `json:"status,omitempty"`
}
